name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          
      - name: Install dependencies
        run: pnpm install
        
      - name: Build
        id: build
        run: pnpm run build
        
      - name: Send Success Notification
        if: success()
        run: |
          curl --request POST \
            --url ${{ secrets.FEISHU_WEBHOOK_URL }} \
            --header 'Content-Type: application/json' \
            --data '{
              "msg_type": "interactive",
              "card": {
                "type": "template",
                "data": {
                  "template_id": "AAqd5SYQzjHxC",
                  "template_version_name": "0.0.1",
                  "template_variable": {
                    "ci_target": "actions-lark-demo",
                    "ci_target_image": "${{ github.repository }}",
                    "ci_target_tag": "${{ github.sha }}",
                    "ci_takes": "${{ steps.build.duration }}",
                    "result_status": "成功",
                    "result_theme": "green"
                  }
                }
              }
            }'
            
      - name: Send Failure Notification
        if: failure()
        run: |
          curl --request POST \
            --url ${{ secrets.FEISHU_WEBHOOK_URL }} \
            --header 'Content-Type: application/json' \
            --data '{
              "msg_type": "interactive",
              "card": {
                "type": "template",
                "data": {
                  "template_id": "AAqd5SYQzjHxC",
                  "template_version_name": "0.0.1",
                  "template_variable": {
                    "ci_target": "actions-lark-demo",
                    "ci_target_image": "${{ github.repository }}",
                    "ci_target_tag": "${{ github.sha }}",
                    "ci_takes": "${{ steps.build.duration }}",
                    "result_status": "失败",
                    "result_theme": "red"
                  }
                }
              }
            }' 